import random


class BatteryCell:

    def __init__(self, cell_id):
        self.cell_id = cell_id
        self.voltage = 3.70
        self.current = 2.0
        self.temperature = 25.0
        self.soc = 40.0
        self.internal_resistance = 0.050

    def update(self, neighbor_temperatures=None):

        # Update state of charge
        self.soc = min(self.soc + 0.5, 100)

        # Update voltage
        self.voltage = min(
            self.voltage + random.uniform(0.001, 0.004),
            4.20
        )

        # Heat generated by the cell itself
        heat_generated = (
            (self.current ** 2)
            * self.internal_resistance
            * 0.05
        )

        # Small random environmental variation
        random_heat = random.uniform(0.005, 0.02)

        # Heat received from neighbouring cells
        heat_transfer = 0.0

        if neighbor_temperatures:

            for neighbor_temperature in neighbor_temperatures:

                temperature_difference = (
                    neighbor_temperature - self.temperature
                )

                # Small amount of heat flows from hotter
                # neighbour to cooler cell
                heat_transfer += 0.02 * temperature_difference

        # Update temperature
        self.temperature += (
            heat_generated
            + random_heat
            + heat_transfer
        )

    def get_state(self, time_step):

        return {
            "Time (s)": time_step,
            "Cell": self.cell_id,
            "Voltage (V)": round(self.voltage, 3),
            "Current (A)": round(self.current, 2),
            "Temperature (°C)": round(self.temperature, 2),
            "SoC (%)": round(self.soc, 2),
            "Internal Resistance (Ω)": round(
                self.internal_resistance,
                4
            )
        }